FROM registry.ci.openshift.org/openshift/release:golang-1.16 as builder

WORKDIR /pushgateway
COPY . .
RUN go mod vendor
RUN make

FROM quay.io/openshift/origin-base:4.8

COPY --from=builder --chown=nobody:nobody /pushgateway/pushgateway /bin/pushgateway

EXPOSE 9091
RUN mkdir -p /pushgateway && chown nobody:nobody /pushgateway
WORKDIR /pushgateway

USER 65534

ENTRYPOINT [ "/bin/pushgateway" ]
